name: Release Published

on:
  workflow_dispatch:
  release:
    types: [ created, edited ]

jobs:
  build_and_publish_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test and build
        run: ./gradlew clean publish

      - name: Print test results
        if: success() || failure()
        run: |
          echo "\n\n*** Wallet SDK test report ***\n"
          cat /home/runner/work/kotlin-wallet-sdk/kotlin-wallet-sdk/wallet-sdk/build/reports/tests/test/index.html
